feat: detect architecture for minio-client feature
ChristopherMacGown/devcontainer-features pull request #14
Opened 2024-10-09 10:19 UTC by kewne

Changes the `architecture` option's default from `amd64` to auto-detection using `uname -m`.

The use case for this is easily supporting a variety of host architectures without having to rely on bespoke environment variables.

2024-10-10 16:32 UTC, ChristopherMacGown requested changes
Hi João, thanks for the pull request! This is a great change, but the output of `uname -m` doesn't match the architecture name that Minio provides. On the test-runners, the output is `x86_64`, but Minio calls that `amd64`. Can you please change that case statement to match the supported architectures that Minio provides?

I've included them here, so you don't have to look at [the site](https://dl.min.io/client/mc/release/)


[linux-amd64/](https://dl.min.io/client/mc/release/linux-amd64/)	-	2024-10-02 20:54
[linux-arm/](https://dl.min.io/client/mc/release/linux-arm/)	-	2024-10-02 20:54
[linux-arm64/](https://dl.min.io/client/mc/release/linux-arm64/)	-	2024-10-02 20:54
[linux-mips64/](https://dl.min.io/client/mc/release/linux-mips64/)	-	2024-10-02 20:54
[linux-ppc64le/](https://dl.min.io/client/mc/release/linux-ppc64le/)	-	2024-10-02 20:54
[linux-s390x/](https://dl.min.io/client/mc/release/linux-s390x/)	-	2024-10-02 20:54

2024-10-11 09:07 UTC, kewne commented
I've added the alias for amd64. I don't really know what the possible outputs are for the other ones though. Looking at https://en.wikipedia.org/wiki/Uname#Examples I also don't see any that would make sense to run in the usual test runners.

Would it be okay to leave it with these two aliases and add new ones whenever someone create an issue for it?

I could also change the fallback clause to fail, instead of trying to passthrough the output of `uname -m`, what do you think?

2024-10-11 17:17 UTC, ChristopherMacGown commented
Let's leave it in place for now, and if someone is running Visual Studio Code on an IBM S390 and `uname -m` doesn't match, they can file a bug 😄

2024-10-11 17:18 UTC, merged

2024-10-11 17:18 UTC, ChristopherMacGown commented
Thanks so much for your contribution! As soon as that build completes, I'll trigger a new release